INSERT INTO HABITAT (HABITAT_ID, TYPE) VALUES (HABITAT_SEQ.NEXTVAL, 'Fresh Water');
INSERT INTO HABITAT (HABITAT_ID, TYPE) VALUES (HABITAT_SEQ.NEXTVAL, 'Brakk Water');
INSERT INTO HABITAT (HABITAT_ID, TYPE) VALUES (HABITAT_SEQ.NEXTVAL, 'Salt Water');

INSERT INTO SPECIES (SPECIES_ID, HABITAT_ID, NAME, CREATION_DATE, LAST_UPDATE_DATE, VERSION) VALUES (SPECIES_SEQ.NEXTVAL, 1, 'Alabrai óriásteknős (Geochelone gigantea)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO SPECIES (SPECIES_ID, HABITAT_ID, NAME, CREATION_DATE, LAST_UPDATE_DATE, VERSION) VALUES (SPECIES_SEQ.NEXTVAL, 2, 'Alamosi iszapteknős (Kinosternon alamosae)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO SPECIES (SPECIES_ID, HABITAT_ID, NAME, CREATION_DATE, LAST_UPDATE_DATE, VERSION) VALUES (SPECIES_SEQ.NEXTVAL, 3, 'Atlanti fattyúteknős (Lepidochelys kempi)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO SPECIES (SPECIES_ID, HABITAT_ID, NAME, CREATION_DATE, LAST_UPDATE_DATE, VERSION) VALUES (SPECIES_SEQ.NEXTVAL, 4, 'Csendes-óceáni levesteknős (Chelonia agassizi)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);

INSERT INTO TURTLE (TURTLE_ID, NAME, SPECIES_ID, WEIGHT, ARRIVAL_DATE, AGE, IS_DELETED, CREATION_DATE, LAST_UPDATE_DATE, VERSION) VALUES (TURTLE_SEQ.NEXTVAL, 'Turtle1', 1, 100, '2024-01-01 00:00:00+00', 1, 'false', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO TURTLE (TURTLE_ID, NAME, SPECIES_ID, WEIGHT, ARRIVAL_DATE, AGE, IS_DELETED, CREATION_DATE, LAST_UPDATE_DATE, VERSION) VALUES (TURTLE_SEQ.NEXTVAL, 'Turtle2', 2, 1000, '2024-02-01 00:00:00+00', 2, 'false', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO TURTLE (TURTLE_ID, NAME, SPECIES_ID, WEIGHT, ARRIVAL_DATE, AGE, IS_DELETED, CREATION_DATE, LAST_UPDATE_DATE, VERSION) VALUES (TURTLE_SEQ.NEXTVAL, 'Turtle3', 2, 10, '2024-07-25 00:00:00+00', 3, 'true', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO TURTLE (TURTLE_ID, NAME, SPECIES_ID, WEIGHT, ARRIVAL_DATE, AGE, IS_DELETED, CREATION_DATE, LAST_UPDATE_DATE, VERSION) VALUES (TURTLE_SEQ.NEXTVAL, 'Turtle4', 4, 200, '2024-07-25 00:00:00+00', 4, 'false', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);