-- Initial Database Creation Script

CREATE TABLE IF NOT EXISTS TURTLE (
  TURTLE_ID BIGINT NOT NULL PRIMARY KEY,
  SPECIES_ID BIGINT NOT NULL,
  NAME VARCHAR(200) NOT NULL,
  ARRIVAL_DATE TIMESTAMP,
  WEIGHT BIGINT NOT NULL,
  AGE BIGINT NOT NULL,
  IS_DELETED BOOLEAN NOT NULL,
  CREATION_DATE TIMESTAMP,
  LAST_UPDATE_DATE TIMESTAMP,
  VERSION BIGINT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS TURTLE_U1 ON TURTLE(TURTLE_ID);
CREATE INDEX IF NOT EXISTS TURTLE_N1 ON TURTLE(NAME);
CREATE INDEX IF NOT EXISTS TURTLE_N2 ON TURTLE(IS_DELETED);
CREATE INDEX IF NOT EXISTS TURTLE_N3 ON TURTLE(SPECIES_ID);

CREATE TABLE IF NOT EXISTS SPECIES (
  SPECIES_ID BIGINT NOT NULL PRIMARY KEY,
  NAME VARCHAR(200) NOT NULL,
  HABITAT_ID BIGINT NOT NULL
  CREATION_DATE TIMESTAMP,
  LAST_UPDATE_DATE TIMESTAMP,
  VERSION BIGINT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS SPECIES_U1 ON SPECIES(SPECIES_ID);

CREATE TABLE IF NOT EXISTS HABITAT (
  HABITAT_ID BIGINT NOT NULL PRIMARY KEY,
  TYPE VARCHAR(200) NOT NULL
  CREATION_DATE TIMESTAMP,
  LAST_UPDATE_DATE TIMESTAMP,
  VERSION BIGINT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS HABITAT_U1 ON HABITAT(HABITAT_ID);

CREATE SEQUENCE IF NOT EXISTS TURTLE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SPECIES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS HABITAT_SEQ START WITH 1 INCREMENT BY 1;